name: Slack analyzer

author: Benjamin Wuethrich

description: Analyze a Slack workspace over time

branding:
  icon: list
  color: orange

inputs:

  name:
    description: Name used in file headings
    required: true

  slack-bot-token:
    description: Slack API bot token with users:read scope
    required: true

  slack-user-token:
    description: Slack API user token with search:read scope
    required: true

outputs:

  diff-msg:
    description: The generated diff, formatted for Telegram
    value: ${{ steps.update.outputs.diff-msg }}

  graph-path:
    description: The path to the PNG of the generated graph
    value: ${{ steps.graph.outputs.path }}

runs:

  using: composite

  steps:

    - name: Update tenures via Slack API
      id: update
      shell: bash
      env:
        BOT_TOKEN: ${{ inputs.slack-bot-token }}
        USER_TOKEN: ${{ inputs.slack-user-token }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email \
            '41898282+github-actions[bot]@users.noreply.github.com'

        '${{ github.action_path }}/scripts/slacktenure' '${{ inputs.name }}'

        if [[ -z $(git status --porcelain) ]]; then
            exit 0
        fi

        git add data/tenures.tsv diffs *.md
        git commit --message="Update tenures"
        git push

        shopt -s globstar

        diffs=(diffs/**/*.diff)
        diff=${diffs[-1]}

        ref=${{ github.ref }}
        ref=${ref##*/}
        baseurl="https://github.com/${{ github.repository }}/blob/$ref"
        links="[Diff]($baseurl/$diff)"
        links+=" • [All tenures]($baseurl/tenures.md)"
        links+=" • [Current tenures]($baseurl/tenurescurrent.md)"
        links+=" • [By duration]($baseurl/tenuresduration.md)"
        printf -v msg '%s\n' "$links" '' '```diff' "$(< "$diff")" '```'
        escapedmsg=$(jq --raw-input --slurp '.' <<< "$msg")

        echo "::set-output name=diff-msg::$escapedmsg"
        echo 'continue=true' >> "$GITHUB_ENV"

    - name: Update graph
      id: graph
      shell: bash
      run: |
        if [[ '${{ env.continue }}' != 'true' ]]; then
            exit 0
        fi

        '${{ github.action_path }}/scripts/generateturnover' \
            data/tenures.tsv > data/turnover.tsv

        if [[ -z $(git status --porcelain) ]]; then
            exit 0
        fi

        sudo apt-get install gnuplot-nox
        echo 'gpinstalled=true' >> "$GITHUB_ENV"
        for type in svg png; do
            gnuplot -c '${{ github.action_path }}/scripts/turnover.gpi' "$type"
        done

        git add data/turnover.tsv turnover.svg
        git commit --message="Update graph"
        git push

        echo "::set-output name=path::turnover.png"

    - name: Update boxplot
      shell: bash
      run: |
        if [[ '${{ env.gpinstalled }}' != 'true' ]]; then
            sudo apt-get install gnuplot-nox
        fi

        source '${{ github.action_path }}/scripts/slacktenure'

        prettyprintduration < data/tenures.tsv \
            | cut --fields=5 \
            | gnuplot '${{ github.action_path }}/scripts/durationboxplot.gpi'

        if [[ -z $(git status --porcelain) ]]; then
            exit 0
        fi

        git add boxplot.svg
        git commit --message="Update boxplot"
        git push
