name: Update tenures

on:
  workflow_dispatch:
  schedule:
    - cron: 0 11,22 * * *

env:
  TZ: America/Toronto

jobs:
  Update:
    name: Update tenures
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4

      - name: Run slacktenure and push changes
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
        run: |
          ./slacktenure 'Tenures at company'
          status=$(git status --porcelain)
          if [[ -n $status ]]; then
              git config --global user.name "github-actions"
              git config --global user.email \
                  "41898282+github-actions[bot]@users.noreply.github.com"
              git add diffs
              git commit --all --message="Update tenures"
              git push
          fi
