name: Update tenures

on:
  workflow_dispatch:
  schedule:
    - cron: 0 11,22 * * *

env:
  TZ: America/Toronto

jobs:
  Update:
    name: Update tenures
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4

      - name: Run slacktenure and push changes
        id: slacktenure
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
        run: |
          ./slacktenure 'Tenures at company'
          status=$(git status --porcelain)
          if [[ -n $status ]]; then
              git config --global user.name 'github-actions'
              git config --global user.email \
                  '41898282+github-actions[bot]@users.noreply.github.com'
              git add diffs
              git commit --all --message="Update tenures"
              git push

              diffs=(diffs/*.diff)
              diff=${diffs[-1]}

              ref=${{ github.ref }}
              ref=${ref##*/}
              baseurl="https://github.com/${{ github.repository }}/blob/$ref"
              links="[Diff]($baseurl/$diff)"
              links+=" • [All tenures]($baseurl/tenures.md)"
              links+=" • [Current tenures]($baseurl/tenurescurrent.md)"
              printf -v msg '%s\n' "$links" '' '```diff' "$(< "$diff")" '```'
              escapedmsg=$(jq --raw-input --slurp '.' <<< "$msg")

              echo "::set-output name=msg::$escapedmsg"
          fi

      - name: Send Telegram message for change
        if: steps.slacktenure.outputs.msg != ''
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: ${{ fromJSON(steps.slacktenure.outputs.msg) }}
